name: Auto Fail

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a one time script
        run: exit 1
